name: art_vault_2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  google_fonts: ^4.0.3
  curved_navigation_bar: ^1.0.0
  provider: ^6.0.1
  day_night_switch: ^1.0.4
  font_awesome_flutter: ^9.1.0
  flutter_sliding_tutorial: ^1.0.3
  carousel_slider: ^4.0.0
  flutter_vector_icons: ^1.0.0
  day_night_switcher: ^0.2.0+1
  swipe_deck: ^1.1.0
  flutter_swiper_view:
  carousel_indicator:
  kf_drawer: ^1.0.0
  lottie: ^1.0.1
  flip_card:
  video_player:
  shared_preferences:
  parallax_effect: ^0.0.3
  intl:
  staggered_grid_view_flutter:
  flutter_staggered_grid_view:
  popover:
  full_screen_image:
  cached_network_image:
  dropdown_search:
  fluttertoast:
  image_picker: ^0.8.4+2
  firebase_storage: ^11.2.7
  photo_manager: ^2.7.1
  liquid_pull_to_refresh: ^3.0.1
  flutter_carousel_slider: ^1.1.0
  chewie:
  card_swiper:





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/cat.jpeg
   - assets/icons/vault.png
   - assets/icons/arrow-left.png
   - assets/icons/home.png
   - assets/icons/house.gif
   - assets/icons/bell.json
   - assets/icons/home1.png
   - assets/icons/user.png
   - assets/icons/user1.png
   - assets/icons/user2.png
   - assets/icons/auction.png
   - assets/icons/auction1.png
   - assets/icons/compass.png
   - assets/icons/compass1.png
   - assets/icons/trending.png
   - assets/icons/trending1.png
   - assets/icons/chat1.png
   - assets/icons/chat.png
   - assets/icons/painter.png
   - assets/icons/mona-lisa.png
   - assets/icons/event.png
   - assets/icons/bookmark.png
   - assets/icons/grid1.png
   - assets/icons/grid2.png
   - assets/icons/grid3.png
   - assets/lotties/placeholder.json
   - assets/lotties/loading.json
   - assets/lotties/load1.json
   - assets/lotties/load2.json
   - assets/lotties/paint.gif
   - assets/lotties/ph.gif
   - assets/lotties/loc.gif
   - assets/lotties/cal.gif
   - assets/avatar.gif
   - assets/lotties/tic.gif
   - assets/lotties/upload.json
   - assets/lotties/golden-loading.json
   - assets/icons/history1.png
   - assets/icons/location.png
   - assets/cat2.jpeg
   - assets/cat3.jpg
   - assets/Card.jpg
   - assets/img3.jpeg
   - assets/5.jpg
   - assets/6.jpg
   - assets/Reading.jfif
   - assets/Pearl.jfif
   - assets/videos/vincent.mp4
   - assets/videos/stary.mp4
   - assets/hands.jpeg
   - assets/painting.json
   - assets/sign.jpg
   - assets/login.webp
   - assets/search.png
   - assets/beige.jpeg
   - assets/logo.gif
   - assets/logo1.gif
   - assets/logo2.gif
   - assets/applogo.png
   - assets/brown.jpg
   - assets/artists.jpeg
   - assets/avatar2.gif
   - assets/pc.json
   - assets/icons/search_ani.gif
   - assets/icons/canvas.png
   - assets/appImages/artworks1.jpeg
   - assets/appImages/artist1.jpeg
   - assets/appImages/artworks1.webp
   - assets/appImages/event1.jpg
   - assets/appImages/eras1.jpeg
   - assets/appImages/museum3.jpeg
   - assets/lotties/waiting.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
